### ISSUE TITLE
MQTT listener does not restart subscription on reconnection

### ISSUE THREAD

**Issue by mdevilliers** [thingful/device-hub#27]
The MQTT library we are using is resilient to dropped TCP connections and will reconnect  unfortunately the it does not restart the subscriptions once reconnected.

I think we need to either -
- keep track of running subscriptions and restart within the listener
- tell the runtime/manager to invalidate all of the running pipes and try to restart them.
- something else

I prefer the second option as it sounds more generic and applicable to other use cases.

**Comment by chespinoza** [comment]
Last night I got this, we have to prevent a panic like this in the server.
```
Christians-MBP:darwin-amd64 christian[client-config-file !?]$ ./device-hub server
2017/07/17 18:59:53 Listening on: [:50051]
2017/07/17 19:04:13 transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:50051->127.0.0.1:59198: read: connection reset by peer
err not found
2017/07/17 22:37:44 mqtt broker connected
2017/07/18 00:56:44 mqtt broker disconnectedpingresp not received, disconnecting
panic: mqtt broker disconnectedpingresp not received, disconnecting

goroutine 1150 [running]:
log.Panic(0xc420031f90, 0x2, 0x2)
	/usr/local/go/src/log/log.go:322 +0xc0
github.com/thingful/device-hub/listener.Register.func1.1(0x1a527a0, 0xc420077180, 0x1a45340, 0xc420202020)
	/Users/christian/go/src/github.com/thingful/device-hub/listener/listeners.go:71 +0xd2
created by github.com/thingful/device-hub/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost
	/Users/christian/go/src/github.com/thingful/device-hub/vendor/github.com/eclipse/paho.mqtt.golang/client.go:418 +0x109
```
